Ignore coercion for unsupported form fields
Currently, using a `<SelectField />`  in a form breaks the form with the error "TypeError: coercionContext.coercions[name] is not a function"